Updated docker file & wrapper cleanup. General cleanup of repository

diff --git a/MDA/mda b/MDA/mda
--- a/MDA/mda
+++ b/MDA/mda
@@ -1,15 +1,5 @@
 #!/usr/bin/env bash
 
-#count_data="~/repos/UA_isala/flow1_redo_revision/data/genus_level_counts.tsv"
-#meta_data="~/repos/UA_isala/flow1_redo_revision/data/metadata.tsv"
-#formula="~/repos/multidiffabundance/example/list_of_functions.txt"
-##formula="~ Reproductive.haschildren + Technical.dna_conc + General.Age"
-#./mda -l "$count_data" "$meta_data" "$formula" "test_output"
-
-source "`dirname $CONDA_EXE`/../etc/profile.d/conda.sh"
-SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
-
-
 ###############################################################################
 
 function usage(){
@@ -39,7 +29,9 @@ function usage(){
 ###############################################################################
 # PROCESS INPUTS
 
-# We use "$@" instead of $* to preserve argument-boundary information
+echo "$@"
+dir
+
 ARGS=$(getopt -o 'aAcdlLm' --long 'aldex2,ancombc,corncob,deseq2,limma,lmclr,maaslin2,complement' -- "$@") || exit
 eval "set -- $ARGS"
 
@@ -136,7 +128,7 @@ if [ `check_if_is_formula "$formula"` -eq 1 ]; then
 fi
 
 
-echo "source('$SCRIPT_DIR/common.R')
+echo "library(multidiffabundance)
     raw.formula.data <- mda.load_formula_input('$formula')
     if(mda.verify_formula_input(raw.formula.data)){
         quit(save='no', status=0)}
@@ -153,55 +145,62 @@ mkdir -p "$outprefix"
 
 ###############################################################################
 
+function run_one_mda(){
+    method=$1
+    
+    echo "[`date`] RUNNING $method"
+    mkdir -p "$outprefix/$method"
+
+    rcode="
+        library(multidiffabundance);
+        library(readr);
+        args = commandArgs(trailingOnly=TRUE);
+        D <- mda.load(args);
+        R <- mda.$method(D);
+        write_tsv(R\$res, paste0(c(D\$outprefix, 'results.tsv'), collapse=''));
+        write_tsv(R\$res.full, paste0(c(D\$outprefix, 'results.full.tsv'), collapse=''))
+    "
+
+    Rscript <(echo "$rcode") "$count_data" "$meta_data" "$formula" "$outprefix/$method/"  > "$outprefix/$method/stdout" 2> "$outprefix/$method/stderr"
+    result=$?
+    
+    if [ $result -eq 0 ]; then
+        echo "[`date`] COMPLETED $method"
+    else
+        echo "[`date`] FAILED $method. See '$outprefix/$method/stderr'"
+    fi
+    return $result
+    
+}
+
 declare -a result_files
 
 if [ $aldex2 -eq 1 ] ; then
-    echo "RUNNING ALDEX2..."
-    mkdir -p "$outprefix/aldex2"
-    conda activate aldex2 && "$SCRIPT_DIR/aldex2/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/aldex2/" > "$outprefix/aldex2/stdout" 2> "$outprefix/aldex2/stderr"
-    result_files+=("$outprefix/aldex2/results.tsv")
+    run_one_mda aldex2 && result_files+=("$outprefix/aldex2/results.tsv")
 fi
 
 if [ $ancombc -eq 1 ] ; then
-    echo "RUNNING ANCOMBC..."
-    mkdir -p "$outprefix/ancombc"
-    conda activate ancom2 && "$SCRIPT_DIR/ancombc/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/ancombc/" > "$outprefix/ancombc/stdout" 2> "$outprefix/ancombc/stderr"
-    result_files+=("$outprefix/ancombc/results.tsv")
+    run_one_mda ancombc && result_files+=("$outprefix/ancombc/results.tsv")
 fi
 
 if [ $corncob -eq 1 ] ; then
-    echo "RUNNING CORNCOB..."
-    mkdir -p "$outprefix/corncob"
-    conda activate corncob && "$SCRIPT_DIR/corncob/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/corncob/" > "$outprefix/corncob/stdout" 2> "$outprefix/corncob/stderr"
-    result_files+=("$outprefix/corncob/results.tsv")
+    run_one_mda corncob && result_files+=("$outprefix/corncob/results.tsv")
 fi
     
 if [ $deseq2 -eq 1 ] ; then
-    echo "RUNNING DESEQ2..."
-    mkdir -p "$outprefix/deseq2"
-    conda activate deseq2 && "$SCRIPT_DIR/deseq2/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/deseq2/" > "$outprefix/deseq2/stdout" 2> "$outprefix/deseq2/stderr"
-    result_files+=("$outprefix/deseq2/results.tsv")
+    run_one_mda deseq2 && result_files+=("$outprefix/deseq2/results.tsv")
 fi
 
 if [ $limma -eq 1 ] ; then
-    echo "RUNNING LIMMA..."
-    mkdir -p "$outprefix/limma"
-    conda activate limma && "$SCRIPT_DIR/limma/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/limma/" > "$outprefix/limma/stdout" 2> "$outprefix/limma/stderr"
-    result_files+=("$outprefix/limma/results.tsv")
+    run_one_mda limma && result_files+=("$outprefix/limma/results.tsv")
 fi
 
 if [ $lmclr -eq 1 ] ; then
-    echo "RUNNING LMCLR..."
-    mkdir -p "$outprefix/lmclr"
-    conda activate limma && "$SCRIPT_DIR/lmclr/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/lmclr/" > "$outprefix/lmclr/stdout" 2> "$outprefix/lmclr/stderr"
-    result_files+=("$outprefix/lmclr/results.tsv")
+    run_one_mda lmclr && result_files+=("$outprefix/lmclr/results.tsv")
 fi
 
 if [ $maaslin2 -eq 1 ] ; then
-    echo "RUNNING MAASLIN2..."
-    mkdir -p "$outprefix/maaslin2"
-    conda activate maaslin2 && "$SCRIPT_DIR/maaslin2/run.sh" "$count_data" "$meta_data" "$formula" "$outprefix/maaslin2/" > "$outprefix/maaslin2/stdout" 2> "$outprefix/maaslin2/stderr"
-    result_files+=("$outprefix/maaslin2/results.tsv")
+    run_one_mda maaslin2 && result_files+=("$outprefix/maaslin2/results.tsv")
 fi
 
 
@@ -214,3 +213,5 @@ head -n 1 "${result_files[0]}" > "$out_file"
 for idx in `seq 0 $((${#result_files[@]}-1))`; do
     tail -n+2 "${result_files[idx]}"
 done >> "$out_file"
+
+echo "[`date`] OUTPUT '$out_file'"
